email: dongphuong2102@gmail.com
phone: (+84) 985 441 031
set_order_num: 5
user:
  name:
    max_length: 50
  email:
    max_length: 50
  password:
    min_length: 6
positon:
  name:
    max_length: 50
  sname:
    max_length: 5
team:
  per_page: 5
  name:
    max_length: 50
